import { Product } from "./product-types";

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: "1",
    name: "Flat White",
    categoryId: "mock-cat-espresso",
    category: "Espresso",
    price: 5.5,
    uom: "Cup",
    tax: "8%",
    active: true,
    imageUrl: "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=600&h=400&fit=crop",
    sizes: ["Small", "Large"],
    defaultSize: "Small",
  },
  {
    id: "2",
    name: "Nitro Cold Brew",
    categoryId: "mock-cat-cold-brew",
    category: "Cold Brew",
    price: 6.5,
    uom: "Can",
    tax: "8%",
    active: true,
    imageUrl: "https://images.unsplash.com/photo-1517701604599-bb29b565090c?w=600&h=400&fit=crop",
    sizes: ["Small", "Large"],
    defaultSize: "Small",
  },
  {
    id: "3",
    name: "Butter Croissant",
    categoryId: "mock-cat-pastries",
    category: "Pastries",
    price: 4.5,
    uom: "Piece",
    tax: "5%",
    active: true,
    imageUrl: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?w=600&h=400&fit=crop",
    sizes: ["Small", "Large"],
    defaultSize: "Small",
  },
  {
    id: "4",
    name: "BLT Club",
    categoryId: "mock-cat-sandwiches",
    category: "Sandwiches",
    price: 11.0,
    uom: "Piece",
    tax: "5%",
    active: true,
    imageUrl: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=600&h=400&fit=crop",
    sizes: ["Small", "Large"],
    defaultSize: "Small",
  },
  {
    id: "5",
    name: "Chai Latte",
    categoryId: "mock-cat-tea",
    category: "Tea",
    price: 5.0,
    uom: "Cup",
    tax: "8%",
    active: false,
    imageUrl: "https://images.unsplash.com/photo-1571934811356-5cc061b6821f?w=600&h=400&fit=crop",
    sizes: ["Small", "Large"],
    defaultSize: "Small",
  },
  {
    id: "6",
    name: "Avocado Toast",
    categoryId: "mock-cat-sandwiches",
    category: "Sandwiches",
    price: 9.0,
    uom: "Plate",
    tax: "5%",
    active: true,
    imageUrl: "https://images.unsplash.com/photo-1525351484163-7529414344d8?w=600&h=400&fit=crop",
    sizes: ["Small", "Large"],
    defaultSize: "Small",
  },
];

export const DEFAULT_PRODUCT_IMAGE =
  "https://images.unsplash.com/photo-1495474472283-4d776bcfdcdb?w=600&h=400&fit=crop";
